apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fpxcxk7r9-nodejs 
  janus-idp.io/tekton: fpxcxk7r9-nodejs
  backstage.io/kubernetes-id: fpxcxk7r9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fpxcxk7r9-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  